Create 0x171f9cFc136f2B2aaA148fcC6b660a2029baB048.json
MyEtherWallet/ethereum-lists pull request #1722
Opened 2021-01-16 02:53 UTC by cjrada

2021-01-23 06:47 UTC, cjrada commented
This PR is ready to be pulled in.  Logo information will come later.  Thanks.

2021-01-25 19:49 UTC, gamalielhere requested changes
Decimal is wrong based on information here: https://www.ethvm.com/token/0x171f9cFc136f2B2aaA148fcC6b660a2029baB048

2021-01-26 06:56 UTC, cjrada commented
> Decimal is wrong based on information here: https://www.ethvm.com/token/0x171f9cFc136f2B2aaA148fcC6b660a2029baB048

Much appreciated.  Updated to 4.

2021-01-26 21:01 UTC, gamalielhere approved these changes

2021-01-27 23:18 UTC, merged