Create 0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE.json
MyEtherWallet/ethereum-lists pull request #1851
Opened 2021-08-13 05:55 UTC by Lucifer712328

2021-08-15 07:21 UTC, mj559940 approved these changes

2021-09-21 00:21 UTC, gamalielhere approved these changes

2021-09-21 00:21 UTC, gamalielhere requested changes
Format is wrong. Please check other token files for correct format.

2021-11-19 22:00 UTC, farmingharry approved these changes

2022-04-28 02:26 UTC, closed without merging