Create 0x8fb1a59ca2d57b51e5971a85277efe72c4492983.json
MyEtherWallet/ethereum-lists pull request #1893
Opened 2021-11-13 01:33 UTC by Frozenjeff

2021-11-13 01:48 UTC, Frozenjeff reviewed
Looks good

2021-11-13 01:59 UTC, zeroturningback approved these changes

2021-11-19 21:58 UTC, farmingharry approved these changes

2021-11-22 17:28 UTC, gamalielhere requested changes
Please move the file in the appropriate network folder, in this case /bsc/

2021-11-22 22:51 UTC, daftoken commented
@gamalielhere I put it in the src/token/bsc folder

2022-03-11 19:35 UTC, closed without merging