Add $DAF Token
MyEtherWallet/ethereum-lists pull request #1896
Opened 2021-11-19 21:44 UTC by daftoken

2021-11-19 21:57 UTC, farmingharry approved these changes

2021-11-19 22:10 UTC, zeroturningback approved these changes

2021-11-19 22:14 UTC, zeroturningback approved these changes
@gamalielhere

2021-11-22 17:27 UTC, gamalielhere requested changes
Please follow the instructions on the provided here: https://github.com/MyEtherWallet/ethereum-lists#tokens

2022-03-11 19:35 UTC, closed without merging