Create $DAF-0x8Fb1a59cA2d57B51e5971A85277EFe72c4492983-bsc.png
MyEtherWallet/ethereum-lists pull request #1900
Opened 2021-11-22 22:45 UTC by daftoken

![$DAF-0x8Fb1a59cA2d57B51e5971A85277EFe72c4492983-bsc](https://user-images.githubusercontent.com/93827367/142946181-4c104027-9735-47d1-bb57-d98c8bf0141e.png)

2021-11-22 22:48 UTC, zeroturningback approved these changes
Added logo

2021-11-30 13:55 UTC, daftoken commented
@gamalielhere

2021-12-09 20:29 UTC, gamalielhere requested changes
this file is invalid https://raw.githubusercontent.com/MyEtherWallet/ethereum-lists/1a4d78f6acc5093595520ba9b81e473780c54d88/master/src/icons/%24DAF-0x8Fb1a59cA2d57B51e5971A85277EFe72c4492983-bsc.png

2021-12-10 21:12 UTC, daftoken commented
Let me know if this one works.

@gamalielhere 


> this file is invalid https://raw.githubusercontent.com/MyEtherWallet/ethereum-lists/1a4d78f6acc5093595520ba9b81e473780c54d88/master/src/icons/%24DAF-0x8Fb1a59cA2d57B51e5971A85277EFe72c4492983-bsc.png
![logo](https://user-images.githubusercontent.com/93827367/145641906-c2e717b4-e71c-4a54-a180-08c510a0b596.png)



![DAF_Logo](https://user-images.githubusercontent.com/93827367/145641823-3c9b11cf-c597-4d6d-94c9-5060b8bccc08.jpg)

2021-12-23 13:51 UTC, daftoken commented
![logo2](https://user-images.githubusercontent.com/93827367/147249700-abd3d19e-5810-43a9-9de2-c100d7e48355.png)

2021-12-23 13:52 UTC, daftoken commented
> this file is invalid https://raw.githubusercontent.com/MyEtherWallet/ethereum-lists/1a4d78f6acc5093595520ba9b81e473780c54d88/master/src/icons/%24DAF-0x8Fb1a59cA2d57B51e5971A85277EFe72c4492983-bsc.png

![logo2](https://user-images.githubusercontent.com/93827367/147249767-fb77065c-fc8c-4a62-b6ab-858e15774d63.png)

2021-12-23 13:52 UTC, daftoken reviewed
![logo2](https://user-images.githubusercontent.com/93827367/147249825-5f5cd52c-d566-4e95-920c-3fd4cfef6ab0.png)

2022-02-09 16:40 UTC, daftoken commented on master/src/icons/$DAF-0x8Fb1a59cA2d57B51e5971A85277EFe72c4492983-bsc.png
> +
![DAF_Logo](https://user-images.githubusercontent.com/93827367/153247036-7d17c26e-4659-4ee3-a788-ecb93c66f2a9.jpg)

[https://raw.githubusercontent.com/daftoken/DAF/main/logo2.png](url)

2022-02-09 16:40 UTC, daftoken commented
@gamalielhere 

https://raw.githubusercontent.com/daftoken/DAF/main/logo2.png

2022-03-11 19:34 UTC, closed without merging